---
- name: Deploy Laravel Application
  hosts: all
  become: yes
  tasks:
    - name: Добавление PPA для PHP 8.2
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Установить необходимые пакеты
      apt:
        name:
          - docker.io
          - docker-compose
          - composer
          - php8.2
          - unzip
          - php8.2-xml
        state: present
      tags: [install]


    - name: pull from git
      git:
        repo: https://github.com/TessiTlesh/ansible-test.git
        dest: /var/www/test
        update: yes
        version: main

    - name: Запустить composer install
      command: composer install
      args:
        chdir: /var/www/test/ansible-laravel


    - name: Запустить Docker Compose
      command: docker-compose up -d
      args:
        chdir: /var/www/test
