---
- name: Deploy Laravel Application
  hosts: all
  become: yes
  tasks:
    - name: Установить необходимые пакеты
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
      tags: [install]


    - name: pull from git
      git:
        repo: https://github.com/TessiTlesh/ansible-test.git
        dest: /var/www/test
        update: yes
        version: main

    - name: Запустить Docker Compose
      command: docker-compose up -d
      args:
        chdir: /var/www/test
